In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('activity1_companies.csv')

In [3]:
df.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,20/20 CUSTOM MOLDED PLASTICS,NaN,NaN,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
1,3-DIMENSIONAL SERVICES GROUP,NaN,Michigan,72,Motor Vehicle Manufacturing,NaN,122200000,3dimensional.com
2,4D SYSTEMS,NaN,Michigan,82,machinery,NaN,$32.5M,4dsysco.com
3,50 FLOOR,NaN,NaN,170,Retail,NaN,65498000,http://www.50floor.com
4,A. STUCKI,NaN,NaN,"501-1,000",Railroad Equipment Manufacturing,NaN,271.6M,http://www.stucki.com

In [4]:
df['Employee Size'].unique()

array(['501-1,000', '72', '82', '170', '201-500', '180', '96', '51-200',
       '130', '73', '59', '335', '79', '99', '81', '890', '632', '230',
       '61', '66', '65', '1,001-5,000', '69', '60', '190', '85', '500',
       '91', '54', '210', '88', '93', '97', '200', '360', '1600', '960',
       '110', '240', '140', '270', '89', '64', '86', '250', '150', '450',
       '94', '1100', '660', '420', '71', '154', '55', '120', '410', '160',
       '92', '310', '490', '63', '520', '970', '67', '430', '56', '740',
       '98', '178', '2300', '68', '380', '260', '650', '460', '582',
       '580', '596', '320', '510', '340', '870', '52', '800', '330',
       '630', '1500', '90', '51', '80', '390', '100', '95', '76', '87',
       '53', '779', '640', '112', '48530', '3000', '57', '350', '213',
       '78', '3800', '370', '62', '75', '220', '58', '501', '3300', '280',
       '7100', '680', '84', '70', '850', '830', '4448', '790', '108',
       '145', '789', '1800', '290', '1000', '77', '770', '540', '1200',
       '910', '440', '920', '750', '83', '990', '4000', '1700', '760',
       '1119', '109', '5,001-10,000', '300', '2083', '5001', '74', '2800',
       '1400', '550', '570', '1300', '810', '798', '940', '860', '1392',
       '620', '2200', '5000', '247', '153', '470', '1900', '600', '1001',
       '5200', '50', '590', '530', '480', 'seven', '11000', '184', '5500',
       '400', '7200', '560', '930', '459', '259', '124', '234', '161'],
      dtype=object)

In [5]:
# Converting alphabetic values in Employee Size to numeric values:
from word2number import w2n
for i in range(len(df)):
    x = str(df.loc[i,'Employee Size'])
    
    if x.isalpha():
        df.loc[i,'Employee Size'] = w2n.word_to_num(df.loc[i,'Employee Size'])
        
    else:
        df.loc[i,'Employee Size'] = df.loc[i,'Employee Size']

df['Employee Size'] = df['Employee Size'].astype(str)

In [6]:
df['Employee Size'].unique()

array(['501-1,000', '72', '82', '170', '201-500', '180', '96', '51-200',
       '130', '73', '59', '335', '79', '99', '81', '890', '632', '230',
       '61', '66', '65', '1,001-5,000', '69', '60', '190', '85', '500',
       '91', '54', '210', '88', '93', '97', '200', '360', '1600', '960',
       '110', '240', '140', '270', '89', '64', '86', '250', '150', '450',
       '94', '1100', '660', '420', '71', '154', '55', '120', '410', '160',
       '92', '310', '490', '63', '520', '970', '67', '430', '56', '740',
       '98', '178', '2300', '68', '380', '260', '650', '460', '582',
       '580', '596', '320', '510', '340', '870', '52', '800', '330',
       '630', '1500', '90', '51', '80', '390', '100', '95', '76', '87',
       '53', '779', '640', '112', '48530', '3000', '57', '350', '213',
       '78', '3800', '370', '62', '75', '220', '58', '501', '3300', '280',
       '7100', '680', '84', '70', '850', '830', '4448', '790', '108',
       '145', '789', '1800', '290', '1000', '77', '770', '540', '1200',
       '910', '440', '920', '750', '83', '990', '4000', '1700', '760',
       '1119', '109', '5,001-10,000', '300', '2083', '5001', '74', '2800',
       '1400', '550', '570', '1300', '810', '798', '940', '860', '1392',
       '620', '2200', '5000', '247', '153', '470', '1900', '600', '1001',
       '5200', '50', '590', '530', '480', '7', '11000', '184', '5500',
       '400', '7200', '560', '930', '459', '259', '124', '234', '161'],
      dtype=object)

In [7]:
# df[df['Employee Size'].str.contains('-')]
df['Employee Size'] = df['Employee Size'].str.replace(',', '')
for i in range(len(df)):
    if '-' in df.loc[i, 'Employee Size']:
        num1= float(df.loc[i,'Employee Size'].split('-')[0])
        num2= float(df.loc[i,'Employee Size'].split('-')[1])

        Emp_avg = int((num1+num2)/2)

        df.loc[i,'Employee Size'] = str(Emp_avg)
    else:
        df.loc[i,'Employee Size'] = df.loc[i,'Employee Size']

In [8]:
df['Employee Size'].unique()

array(['750', '72', '82', '170', '350', '180', '96', '125', '130', '73',
       '59', '335', '79', '99', '81', '890', '632', '230', '61', '66',
       '65', '3000', '69', '60', '190', '85', '500', '91', '54', '210',
       '88', '93', '97', '200', '360', '1600', '960', '110', '240', '140',
       '270', '89', '64', '86', '250', '150', '450', '94', '1100', '660',
       '420', '71', '154', '55', '120', '410', '160', '92', '310', '490',
       '63', '520', '970', '67', '430', '56', '740', '98', '178', '2300',
       '68', '380', '260', '650', '460', '582', '580', '596', '320',
       '510', '340', '870', '52', '800', '330', '630', '1500', '90', '51',
       '80', '390', '100', '95', '76', '87', '53', '779', '640', '112',
       '48530', '57', '213', '78', '3800', '370', '62', '75', '220', '58',
       '501', '3300', '280', '7100', '680', '84', '70', '850', '830',
       '4448', '790', '108', '145', '789', '1800', '290', '1000', '77',
       '770', '540', '1200', '910', '440', '920', '83', '990', '4000',
       '1700', '760', '1119', '109', '7500', '300', '2083', '5001', '74',
       '2800', '1400', '550', '570', '1300', '810', '798', '940', '860',
       '1392', '620', '2200', '5000', '247', '153', '470', '1900', '600',
       '1001', '5200', '50', '590', '530', '480', '7', '11000', '184',
       '5500', '400', '7200', '560', '930', '459', '259', '124', '234',
       '161'], dtype=object)

In [9]:
print(df['Revenue'])

0             58M
1       122200000
2          $32.5M
3        65498000
4          271.6M
          ...
1639         243M
1640         500M
1641    230000000
1642      $457.6M
1643     30402000
Name: Revenue, Length: 1644, dtype: object

In [10]:
revenue_new = []                                 
for i in range(len(df['Revenue'])):     
    if (df.loc[i, 'Revenue'][-1] == 'M'):

        if '.' in df.loc[i, 'Revenue']:
            revenue_new.append(df.loc[i, 'Revenue'][:-1]+'00000')

        else:                        
            revenue_new.append(df.loc[i, 'Revenue'][:-1]+'000000')

    else:
        revenue_new.append(df.loc[i, 'Revenue'])

df['revenue_cleaned'] = revenue_new  

df['revenue_cleaned'] = df['revenue_cleaned'].str.replace('[$.]', '', regex =True)
df['revenue_cleaned'] = df['revenue_cleaned'].astype(int)

# Updating column:
df['Revenue'] = df['revenue_cleaned']
df.drop(columns = ['revenue_cleaned'], inplace = True)

In [11]:
print(df['Revenue'])

0        58000000
1       122200000
2        32500000
3        65498000
4       271600000
          ...
1639    243000000
1640    500000000
1641    230000000
1642    457600000
1643     30402000
Name: Revenue, Length: 1644, dtype: int64

In [12]:
df.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,20/20 CUSTOM MOLDED PLASTICS,NaN,NaN,750,Plastics Manufacturing,NaN,58000000,http://2020cmp.com
1,3-DIMENSIONAL SERVICES GROUP,NaN,Michigan,72,Motor Vehicle Manufacturing,NaN,122200000,3dimensional.com
2,4D SYSTEMS,NaN,Michigan,82,machinery,NaN,32500000,4dsysco.com
3,50 FLOOR,NaN,NaN,170,Retail,NaN,65498000,http://www.50floor.com
4,A. STUCKI,NaN,NaN,750,Railroad Equipment Manufacturing,NaN,271600000,http://www.stucki.com

In [13]:
df.to_csv('activity2_companies.csv', index=False)