In [1]:
import pandas as pd

In [2]:
# CSV to Dataframe:
df = pd.read_csv('companies.csv')

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5536 entries, 0 to 5535
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Company                   5535 non-null   object
 1   Company LinkedIn          1802 non-null   object
 2   Company Location (State)  2600 non-null   object
 3   Employee Size             5536 non-null   object
 4   Industry                  5257 non-null   object
 5   Phone                     748 non-null    object
 6   Revenue                   3016 non-null   object
 7   Website                   5377 non-null   object
dtypes: object(8)
memory usage: 346.1+ KB
None

In [4]:
# Print first 5 rows: 
print(df.head(5))

                        Company                           Company LinkedIn  \
0                    13WHAM ABC                                        NaN
1                    13WHAM ABC  http://www.linkedin.com/company/13wham-tv
2  20/20 CUSTOM MOLDED PLASTICS                                        NaN
3  20/20 CUSTOM MOLDED PLASTICS  https://www.linkedin.com/company/15516558
4                     3 UNDER 3                                        NaN

  Company Location (State) Employee Size                Industry Phone  \
0                      NaN            79        Media Production   NaN
1                      NaN            79        Media Production   NaN
2                      NaN     501-1,000  Plastics Manufacturing   NaN
3                     Ohio     501-1,000  Plastics Manufacturing   NaN
4                      NaN           one                     NaN   NaN

  Revenue              Website
0     NaN  https://13wham.com/
1     NaN  https://13wham.com/
2     58M   http://2020cmp.com
3     58M   http://2020cmp.com
4     NaN                  NaN

In [5]:
# Print last 5 rows: 
print(df.tail(5))

                                                Company  \
5531                                               ZOLL
5532                                            ZUMBIEL
5533                                            ZUMBIEL
5534                                                NaN
5535  Applied filters:\nCompany Count is greater tha...

                                       Company LinkedIn  \
5531  https://www.linkedin.com/company/zoll-medical-...
5532                                                NaN
5533                                                NaN
5534                                                NaN
5535                                                NaN

     Company Location (State) Employee Size                         Industry  \
5531            Massachusetts   1,001-5,000  Medical Equipment Manufacturing
5532                      NaN           161           Packaging & Containers
5533                 Kentucky           161           Packaging & Containers
5534                      NaN          four                              NaN
5535                      NaN           ten                              NaN

     Phone   Revenue                Website
5531   NaN   $457.6M  https://www.zoll.com/
5532   NaN  30402000            zumbiel.com
5533   NaN  30402000            zumbiel.com
5534   NaN       NaN                    NaN
5535   NaN       NaN                    NaN

In [6]:
# Display all columns:
print(df.columns)

Index(['Company', 'Company LinkedIn', 'Company Location (State)',
       'Employee Size', 'Industry', 'Phone', 'Revenue', 'Website'],
      dtype='object')

In [7]:
# Change display max width:
pd.set_option('display.max_columns', None)
df.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,13WHAM ABC,NaN,NaN,79,Media Production,NaN,NaN,https://13wham.com/
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,NaN,79,Media Production,NaN,NaN,https://13wham.com/
2,20/20 CUSTOM MOLDED PLASTICS,NaN,NaN,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
4,3 UNDER 3,NaN,NaN,one,NaN,NaN,NaN,NaN

In [8]:
# Fill all 'NaN' values with 0 & remove duplicate rows:
df_clean = df.fillna(0)
df_clean.drop_duplicates(inplace= True)

In [9]:
# Resetting the index and discarding old index value:
df_clean.reset_index(inplace=True)
df_clean.drop(columns=['index'],inplace=True)
df_clean.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,13WHAM ABC,0,0,79,Media Production,0,0,https://13wham.com/
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,0,79,Media Production,0,0,https://13wham.com/
2,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com
4,3 UNDER 3,0,0,one,0,0,0,0

In [10]:
df_clean.tail()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
5513,ZOLL,https://www.linkedin.com/company/zoll-medical-...,Massachusetts,"1,001-5,000",Medical Equipment Manufacturing,0,$457.6M,https://www.zoll.com/
5514,ZUMBIEL,0,0,161,Packaging & Containers,0,30402000,zumbiel.com
5515,ZUMBIEL,0,Kentucky,161,Packaging & Containers,0,30402000,zumbiel.com
5516,0,0,0,four,0,0,0,0
5517,Applied filters:\nCompany Count is greater tha...,0,0,ten,0,0,0,0

In [11]:
df_clean.count()

Company                     5518
Company LinkedIn            5518
Company Location (State)    5518
Employee Size               5518
Industry                    5518
Phone                       5518
Revenue                     5518
Website                     5518
dtype: int64

In [12]:
# Checking data type of a random row:
print(df_clean['Company'][500],type(df_clean['Company'][500]))
print(df_clean['Company LinkedIn'][500], type(df_clean['Company LinkedIn'][500]))
print(df_clean['Company Location (State)'][500],type(df_clean['Company Location (State)'][500]))
print(df_clean['Employee Size'][500],type(df_clean['Employee Size'][500]))
print(df_clean['Industry'][500], type(df_clean['Industry'][500]))
print(df_clean['Phone'][500], type(df_clean['Phone'][500]))
print(df_clean['Revenue'][500], type(df_clean['Revenue'][500]))
print(df_clean['Website'][500],type(df_clean['Website'][500]))

AUBURN UNIVERSITY HARBERT COLLEGE OF BUSINESS <class 'str'>
https://www.linkedin.com/school/auburn-university-raymond-j.-harbert-college-of-business/ <class 'str'>
0 <class 'int'>
201-500 <class 'str'>
Higher Education <class 'str'>
0 <class 'int'>
0 <class 'int'>
https://harbert.auburn.edu/ <class 'str'>

In [13]:
# Casting all the fields to string data type:
df_clean[['Company', 'Company LinkedIn', 'Company Location (State)','Employee Size','Industry', 'Phone','Revenue', 'Website']] = df_clean[['Company', 'Company LinkedIn', 'Company Location (State)','Employee Size','Industry', 'Phone','Revenue', 'Website']].astype(str)

In [14]:
# Verifying casting was done correctly:
print(df_clean['Company'][500],type(df_clean['Company'][500]))
print(df_clean['Company LinkedIn'][500], type(df_clean['Company LinkedIn'][500]))
print(df_clean['Company Location (State)'][500],type(df_clean['Company Location (State)'][500]))
print(df_clean['Employee Size'][500],type(df_clean['Employee Size'][500]))
print(df_clean['Industry'][500], type(df_clean['Industry'][500]))
print(df_clean['Phone'][500], type(df_clean['Phone'][500]))
print(df_clean['Revenue'][500], type(df_clean['Revenue'][500]))
print(df_clean['Website'][500],type(df_clean['Website'][500]))

AUBURN UNIVERSITY HARBERT COLLEGE OF BUSINESS <class 'str'>
https://www.linkedin.com/school/auburn-university-raymond-j.-harbert-college-of-business/ <class 'str'>
0 <class 'str'>
201-500 <class 'str'>
Higher Education <class 'str'>
0 <class 'str'>
0 <class 'str'>
https://harbert.auburn.edu/ <class 'str'>

In [15]:
df_clean['Revenue'].value_counts()

Revenue
0           2502
300M          47
25000000      47
50000000      44
75M           40
            ...
$63M           1
$44.2M         1
65800000       1
$29.6M         1
96800000       1
Name: count, Length: 1109, dtype: int64

In [16]:
# Created a new field 'revenue_cleaned' from 'Revenue'
# Replaced 'M' with '000000' to convert the values into numeric values
# Eg. 25M -> 25000000
          
revenue_new = []                                 
for i in range(len(df_clean['Revenue'])):                 
    if (df_clean['Revenue'][i] == '0'):
        revenue_new.append(df_clean['Revenue'][i])
    else:
        if (df_clean['Revenue'][i][-1] == 'M'):                            
            revenue_new.append(df_clean['Revenue'][i][:-1]+'000000')
        else:
            revenue_new.append(df_clean['Revenue'][i])

df_clean['revenue_cleaned'] = revenue_new  
df_clean.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website,revenue_cleaned
0,13WHAM ABC,0,0,79,Media Production,0,0,https://13wham.com/,0
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,0,79,Media Production,0,0,https://13wham.com/,0
2,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com,58000000
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com,58000000
4,3 UNDER 3,0,0,one,0,0,0,0,0

In [17]:
df_clean['revenue_cleaned'].value_counts()

revenue_cleaned
0              2502
100000000        73
50000000         70
40000000         68
75000000         65
               ...
419400000         1
$34000000         1
$31.4000000       1
$30.4000000       1
26109000          1
Name: count, Length: 1045, dtype: int64

In [18]:
# Removed '.' and '$' from the new field 'revenue_new' and casted it to type integer:
df_clean['revenue_cleaned'] = df_clean['revenue_cleaned'].str.replace('[$.]', '', regex =True)
df_clean['revenue_cleaned'] = df_clean['revenue_cleaned'].astype(int)

In [19]:
# Updating column:
df_clean['Revenue'] = df_clean['revenue_cleaned']
# Droping column:
df_clean.drop(columns = ['revenue_cleaned'], inplace = True)

In [20]:
# Getting the statistical values - mean, std, min, max:
stats = df_clean.describe().reset_index()
print(type(stats))
print(stats)

<class 'pandas.core.frame.DataFrame'>
   index       Revenue
0  count  5.518000e+03
1   mean  2.454098e+08
2    std  6.178613e+08
3    min  0.000000e+00
4    25%  0.000000e+00
5    50%  3.100000e+07
6    75%  2.445000e+08
7    max  5.820000e+09

In [21]:
# Getting the median:
median_val  = df_clean['Revenue'].median()
median_val = pd.Series(median_val)
print(type(median_val))
print(median_val)

<class 'pandas.core.series.Series'>
0    31000000.0
dtype: float64

In [22]:
# Added 'median_val' as a row to the 'stats' dataframe:
stats= pd.concat([stats, median_val.to_frame()], ignore_index=True)
print(stats)

   index       Revenue           0
0  count  5.518000e+03         NaN
1   mean  2.454098e+08         NaN
2    std  6.178613e+08         NaN
3    min  0.000000e+00         NaN
4    25%  0.000000e+00         NaN
5    50%  3.100000e+07         NaN
6    75%  2.445000e+08         NaN
7    max  5.820000e+09         NaN
8    NaN           NaN  31000000.0

In [23]:
# Renamed column 'index' as 'Stats':
stats.rename(columns= {'index':'revenue_stats'}, inplace= True)

In [24]:
# Renamed column 'Revenue' as 'values':
stats.rename(columns= {'Revenue': 'values'}, inplace= True)

In [25]:
# Updated the median value correctly:
stats['revenue_stats'][8] = 'median'
stats['values'][8] = stats[0][8]
stats.drop(columns= [0], inplace= True)
stats

C:\Users\yania\AppData\Local\Temp\ipykernel_3956\1251150113.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stats['revenue_stats'][8] = 'median'
C:\Users\yania\AppData\Local\Temp\ipykernel_3956\1251150113.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['revenue_stats'][8] = 'median'
C:\Users\yania\AppData\Local\Temp\ipykernel_3956\1251150113.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stats['values'][8] = stats[0][8]
C:\Users\yania\AppData\Local\Temp\ipykernel_3956\1251150113.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['values'][8] = stats[0][8]

  revenue_stats        values
0         count  5.518000e+03
1          mean  2.454098e+08
2           std  6.178613e+08
3           min  0.000000e+00
4           25%  0.000000e+00
5           50%  3.100000e+07
6           75%  2.445000e+08
7           max  5.820000e+09
8        median  3.100000e+07

In [26]:
# Print CSV stats (mean, median, min, max, etc.,):
stats = stats.to_csv('stats_values.csv')

In [27]:
# Print a specific column:
print(df_clean['Employee Size'])

0                79
1                79
2         501-1,000
3         501-1,000
4               one
           ...
5513    1,001-5,000
5514            161
5515            161
5516           four
5517            ten
Name: Employee Size, Length: 5518, dtype: object

In [28]:
# Print unique values:
size_unique = df_clean['Employee Size'].unique()
print(size_unique)

['79' '501-1,000' 'one' 'seven' 'three' '72' '82' '170' 'ten' '201-500'
 '10,001+' '1,001-5,000' '180' '96' '51-200' 'nine' '0' 'two' '130' '73'
 '59' '335' '99' '81' '8' '890' '632' '230' '61' 'six' '66' '65' '11-50'
 '2-10' '2' '69' '60' '190' '85' '19000' 'five' '200' '500' '201' '91'
 '54' '210' '88' '93' '97' 'eight' '192' '1,001-5,000 employees' '155000'
 'four' '360' '57' '650' '30' '1600' '960' '110' '240' '140' '270' '520'
 '89' '64' '6100' '86' '250' '640' '150' '450' '94' '370' '232' '6900'
 '1100' '660' '420' '71' '154' '84' '55' '120' '410' '160'
 '10,001+ employees' '5' '92' '310' '1800' '5,001-10,000' '490' '63' '62'
 '25' '970' '11000' '2000' '67' '470' '430' '280' '56' '11-50 employees'
 '4800' '740' '26' '98' '178' '2300' '68' '680' '380' '260' '20' '460'
 '582' '580' '13' '6' '596' '16' '320' '43' '510' '2900' '340' '48000'
 '870' '52' '51' '15' '800' '501' '330' '30000' '247' '630' '1500'
 '201-500 employees' '90' '80' '390' '100' '501-1,000 employees' '1300'
 '95' '2/10/2023' '690' '76' '11' '39' '12' '87' '53' '779' '112' '1'
 '48530' '37' '3000' '400' '350' '213' '83000' '78' '990' '3800' '18' '75'
 '220' '58' '3300' '126' '39000' '7100' '70' '850' '104' '830' '12000' '3'
 '4448' '790' '1705' '316000' '142' '36' '5600' '499' '108' '129000' '145'
 '789' '22' '290' '1000' '77' '17' '770' '540' '1200' '910' '440' '920'
 '6/8/1900' '0-1' '750' '83' '6/28/1900' '4000' '378' '10' '35000' '24'
 '1700' '760' '1119' '109' '4/19/1900' '300' '2500' '9/26/1900' '2083'
 '5001' '74' '2800' '1400' '550' '570' '13000' '9' '14' '31000' '810'
 '<25' '700' '798' '940' '860' '1392' '618' '620' '2200' '5000' '153'
 '2400' '600' '51-20' '45' '480' '1900' '2100' '5,001-10,000 employees'
 '1001' '5200' '50' '8100' '3500' '20000' '42' '590' '530' '1175' '40'
 '18000' '108000' '4' '3600' '184' '5500' '101000' '40000' '34' '4200'
 '165' '7200' '104000' '560' '930' '14000' '204' '459' '4300' '259'
 '4/4/1901' '124' '234' '2300000' '161']

In [29]:
pd.set_option('display.max_rows',None)
df_clean['Employee Size'].value_counts()

Employee Size
201-500                   898
51-200                    497
501-1,000                 487
1,001-5,000               341
10,001+                   147
120                        86
200                        81
11-50                      72
170                        71
5,001-10,000               69
seven                      68
130                        59
nine                       58
three                      57
one                        57
110                        55
150                        55
2-10                       54
six                        49
four                       47
ten                        46
two                        46
160                        45
five                       43
180                        42
eight                      41
140                        41
51                         40
79                         34
210                        32
230                        29
67                         28
63                         28
52                         28
54                         27
370                        26
190                        25
73                         25
61                         25
270                        25
68                         24
2/10/2023                  23
59                         23
500                        22
280                        22
62                         21
71                         21
250                        21
65                         20
93                         20
94                         19
77                         19
1100                       18
88                         18
66                         18
69                         18
57                         17
85                         17
78                         16
55                         16
420                        16
64                         15
72                         15
58                         14
98                         14
76                         14
97                         14
650                        14
53                         13
390                        13
89                         13
70                         13
91                         13
520                        13
84                         12
6                          12
56                         12
86                         12
80                         12
96                         12
340                        12
1                          12
1600                       12
460                        12
60                         12
410                        11
380                        11
240                        11
490                        11
5000                       10
75                         10
360                        10
310                        10
260                        10
990                        10
74                         10
99                          9
83                          9
300                         9
0                           9
570                         9
290                         9
100                         9
90                          9
82                          9
870                         8
630                         8
1500                        8
680                         8
1900                        8
1200                        8
400                         8
220                         8
2300                        7
92                          7
320                         7
501                         7
1000                        7
5001                        7
620                         7
750                         7
970                         7
26                          7
11000                       7
1400                        7
582                         6
560                         6
470                         6
1800                        6
330                         6
640                         6
20                          6
5500                        6
3000                        6
1300                        6
3                           6
4000                        6
770                         6
2                           6
201                         6
580                         6
430                         6
4                           6
760                         6
890                         6
81                          6
1175                        5
1001                        5
1,001-5,000 employees       5
480                         5
800                         5
10,001+ employees           5
830                         4
0-1                         4
540                         4
18                          4
350                         4
660                         4
95                          4
30                          4
596                         4
30000                       4
2900                        4
15                          4
378                         4
42                          4
10                          4
810                         4
860                         4
145                         4
910                         4
234                         4
178                         3
39                          3
789                         3
501-1,000 employees         3
600                         3
940                         3
24                          3
2083                        3
108                         3
247                         3
4300                        3
459                         2
14000                       2
4200                        2
7200                        2
104000                      2
930                         2
4800                        2
2000                        2
259                         2
25                          2
101000                      2
184                         2
34                          2
40000                       2
18000                       2
8100                        2
5200                        2
1392                        2
6100                        2
48000                       2
450                         2
6900                        2
154                         2
510                         2
16                          2
13                          2
740                         2
11-50 employees             2
43                          2
5                           2
4448                        2
12000                       2
17                          2
7100                        2
39000                       2
3300                        2
83000                       2
850                         2
37                          2
48530                       2
213                         2
3800                        2
12                          2
11                          2
87                          2
690                         2
2300000                     2
40                          2
3600                        2
50                          2
31000                       2
700                         2
8                           2
798                         2
19000                       2
5600                        2
316000                      2
36                          2
129000                      2
22                          2
920                         2
440                         2
790                         2
960                         2
112                         2
155000                      2
779                         2
2500                        2
14                          2
13000                       2
632                         2
335                         2
550                         2
2800                        2
109                         2
1119                        2
1700                        2
35000                       2
161                         2
124                         2
108000                      2
2100                        2
590                         2
530                         2
20000                       2
3500                        2
9                           2
51-20                       2
2400                        2
618                         2
45                          2
153                         2
2200                        2
204                         1
232                         1
201-500 employees           1
165                         1
499                         1
1705                        1
192                         1
126                         1
104                         1
6/28/1900                   1
6/8/1900                    1
142                         1
9/26/1900                   1
<25                         1
4/19/1900                   1
5,001-10,000 employees      1
4/4/1901                    1
Name: count, dtype: int64

Slicing:

In [30]:
# Create calculated field:
company_type = []
for i in range(len(df_clean)):
    if ((df_clean['Revenue'][i] < 38500000)and((df_clean['Employee Size'][i] == '51-200')|(df_clean['Employee Size'][i] == '201-500')|(df_clean['Employee Size'][i] == '501-1000'))):
        x = 'Small Enterprise'
        company_type.append(x)

    elif ((38500000 <=df_clean['Revenue'][i] < 1000000000)&((df_clean['Employee Size'][i] == '1,001-5,000')|(df_clean['Employee Size'][i] == '5,001-10,000'))):
        x = 'Medium Enterprise'
        company_type.append(x)

    elif ((df_clean['Revenue'][i] >= 1000000000)&(df_clean['Employee Size'][i] == '10,001+')):
        x= 'Large Enterprise'
        company_type.append(x)
    else:
        x = ''
        company_type.append(x)
 
df_clean['Company type'] = company_type

In [31]:
df_clean.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website,Company type
0,13WHAM ABC,0,0,79,Media Production,0,0,https://13wham.com/,
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,0,79,Media Production,0,0,https://13wham.com/,
2,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58000000,http://2020cmp.com,
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,0,58000000,http://2020cmp.com,
4,3 UNDER 3,0,0,one,0,0,0,0,

In [32]:
# Filter onrow:
df_clean[df_clean['Company type'] != ''][:10]

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website,Company type
21,A.O. REED & CO.,0,0,201-500,Construction,0,0,https://aoreed.com/,Small Enterprise
22,A.O. REED & CO.,https://www.linkedin.com/company/ao-reed/,0,201-500,Construction,0,0,https://aoreed.com/,Small Enterprise
152,AIRLINE HYDRAULICS,0,0,201-500,Industrial Automation,0,30000000,https://www.airlinehyd.com/,Small Enterprise
153,AIRLINE HYDRAULICS,https://www.linkedin.com/company/543132,Pennsylvania,201-500,Industrial Automation,0,30000000,https://www.airlinehyd.com/,Small Enterprise
174,ALABAMA TECHNOLOGY NETWORK,0,0,51-200,Professional Training and Coaching,0,0,https://www.atn.org/,Small Enterprise
175,ALABAMA TECHNOLOGY NETWORK,https://www.linkedin.com/company/alabama-techn...,0,51-200,Professional Training and Coaching,0,0,https://www.atn.org/,Small Enterprise
203,ALLIANCE PHARMA,0,0,201-500,Pharmaceutical Manufacturing,0,32000000,http://www.alliancepharmaco.com/,Small Enterprise
204,ALLIANCE PHARMA,https://www.linkedin.com/company/9355645,Pennsylvania,201-500,Pharmaceutical Manufacturing,0,32000000,http://www.alliancepharmaco.com/,Small Enterprise
231,ALLYALIGN HEALTH,0,0,51-200,Hospitals and Health Care,0,0,https://www.allyalign.com/,Small Enterprise
232,ALLYALIGN HEALTH,https://www.linkedin.com/company/allyalign-hea...,0,51-200,Hospitals and Health Care,0,0,https://www.allyalign.com/,Small Enterprise

In [33]:
# Delete/output