In [1]:
import pandas as pd

In [2]:
# CSV to Dataframe:
df = pd.read_csv('companies.csv')

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5536 entries, 0 to 5535
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Company                   5535 non-null   object
 1   Company LinkedIn          1802 non-null   object
 2   Company Location (State)  2600 non-null   object
 3   Employee Size             5536 non-null   object
 4   Industry                  5257 non-null   object
 5   Phone                     748 non-null    object
 6   Revenue                   3016 non-null   object
 7   Website                   5377 non-null   object
dtypes: object(8)
memory usage: 346.1+ KB
None

In [4]:
# Print first 5 rows: 
print(df.head(5))

                        Company                           Company LinkedIn  \
0                    13WHAM ABC                                        NaN
1                    13WHAM ABC  http://www.linkedin.com/company/13wham-tv
2  20/20 CUSTOM MOLDED PLASTICS                                        NaN
3  20/20 CUSTOM MOLDED PLASTICS  https://www.linkedin.com/company/15516558
4                     3 UNDER 3                                        NaN

  Company Location (State) Employee Size                Industry Phone  \
0                      NaN            79        Media Production   NaN
1                      NaN            79        Media Production   NaN
2                      NaN     501-1,000  Plastics Manufacturing   NaN
3                     Ohio     501-1,000  Plastics Manufacturing   NaN
4                      NaN           one                     NaN   NaN

  Revenue              Website
0     NaN  https://13wham.com/
1     NaN  https://13wham.com/
2     58M   http://2020cmp.com
3     58M   http://2020cmp.com
4     NaN                  NaN

In [5]:
# Print last 5 rows: 
print(df.tail(5))

                                                Company  \
5531                                               ZOLL
5532                                            ZUMBIEL
5533                                            ZUMBIEL
5534                                                NaN
5535  Applied filters:\nCompany Count is greater tha...

                                       Company LinkedIn  \
5531  https://www.linkedin.com/company/zoll-medical-...
5532                                                NaN
5533                                                NaN
5534                                                NaN
5535                                                NaN

     Company Location (State) Employee Size                         Industry  \
5531            Massachusetts   1,001-5,000  Medical Equipment Manufacturing
5532                      NaN           161           Packaging & Containers
5533                 Kentucky           161           Packaging & Containers
5534                      NaN          four                              NaN
5535                      NaN           ten                              NaN

     Phone   Revenue                Website
5531   NaN   $457.6M  https://www.zoll.com/
5532   NaN  30402000            zumbiel.com
5533   NaN  30402000            zumbiel.com
5534   NaN       NaN                    NaN
5535   NaN       NaN                    NaN

In [6]:
# Display all columns:
print(df.columns)

Index(['Company', 'Company LinkedIn', 'Company Location (State)',
       'Employee Size', 'Industry', 'Phone', 'Revenue', 'Website'],
      dtype='object')

In [7]:
# Change display max width:
pd.set_option('display.max_columns', None)
df.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,13WHAM ABC,NaN,NaN,79,Media Production,NaN,NaN,https://13wham.com/
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,NaN,79,Media Production,NaN,NaN,https://13wham.com/
2,20/20 CUSTOM MOLDED PLASTICS,NaN,NaN,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
4,3 UNDER 3,NaN,NaN,one,NaN,NaN,NaN,NaN

In [8]:
# Removed all rows with no revenue value:
df_clean = df.dropna(subset= 'Revenue')
df_clean

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
2,20/20 CUSTOM MOLDED PLASTICS,NaN,NaN,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
7,3-DIMENSIONAL SERVICES GROUP,NaN,Michigan,72,Motor Vehicle Manufacturing,NaN,122200000,3dimensional.com
9,4D SYSTEMS,NaN,Michigan,82,machinery,NaN,$32.5M,4dsysco.com
12,50 FLOOR,NaN,NaN,170,Retail,NaN,65498000,http://www.50floor.com
...,...,...,...,...,...,...,...,...
5522,ZIPPO MANUFACTURING COMPANY,NaN,Pennsylvania,570,Mechanical Or Industrial Engineering,NaN,230000000,zippo.com
5530,ZOLL,NaN,NaN,"1,001-5,000",Medical Equipment Manufacturing,NaN,$457.6M,https://www.zoll.com/
5531,ZOLL,https://www.linkedin.com/company/zoll-medical-...,Massachusetts,"1,001-5,000",Medical Equipment Manufacturing,NaN,$457.6M,https://www.zoll.com/
5532,ZUMBIEL,NaN,NaN,161,Packaging & Containers,NaN,30402000,zumbiel.com
5533,ZUMBIEL,NaN,Kentucky,161,Packaging & Containers,NaN,30402000,zumbiel.com

In [9]:
# Fill the 'NaN' values with 0 & remove duplicate rows:
df_clean = df_clean.fillna('0')
df_clean.drop_duplicates(inplace= True)

In [10]:
# Resetting the index and discarding old index value:
df_clean.reset_index(drop=True, inplace=True)
df_clean.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com
1,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com
2,3-DIMENSIONAL SERVICES GROUP,0,Michigan,72,Motor Vehicle Manufacturing,0,122200000,3dimensional.com
3,4D SYSTEMS,0,Michigan,82,machinery,0,$32.5M,4dsysco.com
4,50 FLOOR,0,0,170,Retail,0,65498000,http://www.50floor.com

In [11]:
df_clean.tail()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
3011,ZIPPO MANUFACTURING COMPANY,0,Pennsylvania,570,Mechanical Or Industrial Engineering,0,230000000,zippo.com
3012,ZOLL,0,0,"1,001-5,000",Medical Equipment Manufacturing,0,$457.6M,https://www.zoll.com/
3013,ZOLL,https://www.linkedin.com/company/zoll-medical-...,Massachusetts,"1,001-5,000",Medical Equipment Manufacturing,0,$457.6M,https://www.zoll.com/
3014,ZUMBIEL,0,0,161,Packaging & Containers,0,30402000,zumbiel.com
3015,ZUMBIEL,0,Kentucky,161,Packaging & Containers,0,30402000,zumbiel.com

In [12]:
df_clean.count()

Company                     3016
Company LinkedIn            3016
Company Location (State)    3016
Employee Size               3016
Industry                    3016
Phone                       3016
Revenue                     3016
Website                     3016
dtype: int64

In [13]:
df_clean['Revenue'].value_counts()

Revenue
25000000    47
300M        47
50000000    44
75M         40
40M         40
            ..
39900000     1
$32.5M       1
$34M         1
$31.4M       1
$44.2M       1
Name: count, Length: 1108, dtype: int64

In [14]:
# Created a new field 'revenue_cleaned' from 'Revenue'
# Replaced 'M' with '000000' to convert the values into numeric values
# Eg. 25M -> 25000000
          
revenue_new = []                                 
for i in range(len(df_clean['Revenue'])):                 
    if (df_clean['Revenue'][i][-1] == 'M'):
        if '.' in df_clean['Revenue'][i]:
            print(df_clean['Revenue'][i])
            revenue_new.append(df_clean['Revenue'][i][:-1]+'00000')
        else:                        
            revenue_new.append(df_clean['Revenue'][i][:-1]+'000000')
    else:
        revenue_new.append(df_clean['Revenue'][i])

df_clean['revenue_cleaned'] = revenue_new  
df_clean.head()

$32.5M
271.6M
271.6M
271.6M
271.6M
120.8M
120.8M
286.1M
286.1M
$69.6M
$69.6M
36.2M
36.2M
46.9M
46.9M
42.5M
42.5M
$75.5M
33.8M
33.8M
107.5M
107.5M
35.5M
35.5M
188.2M
188.2M
$27.3M
117.8M
117.8M
63.3M
63.3M
40.3M
40.3M
$190.1M
$274.1M
38.7M
38.7M
$155.3M
93.8M
93.8M
45.1M
45.1M
98.9M
98.9M
39.1M
39.1M
82.4M
82.4M
65.5M
65.5M
59.8M
59.8M
$31.9M
$31.9M
$292.3M
$292.3M
231.5M
231.5M
$77.7M
$77.7M
$217.3M
$217.3M
$25.0M
54.8M
54.8M
$108.6M
$108.6M
$61.3M
$61.3M
53.7M
53.7M
55.4M
55.4M
$34.9M
$34.9M
30.5M
30.5M
$121.3M
250.5M
250.5M
$26.4M
188.4M
188.4M
42.1M
42.1M
$497.6M
217.9M
217.9M
330.4M
330.4M
44.1M
44.1M
$54.3M
$54.3M
$53.0M
$84.5M
$84.5M
$32.0M
60.2M
60.2M
64.6M
64.6M
59.2M
59.2M
43.4M
43.4M
14.6M
14.6M
$93.7M
$93.7M
34.7M
34.7M
$417.4M
$417.4M
$113.2M
$113.2M
69.9M
69.9M
32.4M
32.4M
5.8M
5.8M
$41.4M
$41.4M
93.4M
93.4M
97.8M
97.8M
$142.6M
$142.6M
12.1M
12.1M
$68.4M
35.4M
35.4M
$215.7M
$215.7M
$75.0M
$185.5M
$185.5M
39.6M
39.6M
$176.3M
$176.3M
56.3M
56.3M
218.1M
218.1M
130.4M
130.4M
111.9M
111.9M
94.5M
94.5M
61.1M
61.1M
30.2M
30.2M
$54.7M
$54.7M
$324.4M
77.5M
77.5M
51.9M
51.9M
$80.3M
$80.3M
58.9M
58.9M
85.2M
85.2M
$352.8M
$26.5M
43.0M
43.0M
471.1M
471.1M
31.9M
31.9M
$34.1M
$34.1M
$79.3M
$79.3M
$55.2M
$55.2M
151.3M
151.3M
$25.8M
40.2M
40.2M
117.4M
117.4M
$32.6M
122.5M
122.5M
46.4M
46.4M
37.9M
37.9M
40.1M
40.1M
$279.5M
$279.5M
473.8M
473.8M
42.9M
42.9M
$97.3M
77.4M
77.4M
$30.6M
39.6M
39.6M
50.1M
50.1M
117.4M
117.4M
$25.0M
$57.9M
$57.9M
59.3M
59.3M
70.7M
70.7M
41.2M
41.2M
36.4M
36.4M
53.8M
53.8M
52.7M
52.7M
$127.3M
$127.3M
271.6M
271.6M
$26.6M
$122.5M
$122.5M
$582.0M
34.0M
34.0M
325.2M
325.2M
218.7M
218.7M
$50.5M
$50.5M
78.1M
78.1M
201.7M
201.7M
450.2M
450.2M
$25.4M
34.1M
34.1M
166.6M
166.6M
30.3M
30.3M
$46.3M
104.6M
104.6M
92.7M
92.7M
98.7M
98.7M
41.1M
41.1M
$35.0M
$69.6M
131.2M
131.2M
64.3M
64.3M
34.4M
34.4M
$65.6M
355.3M
355.3M
67.9M
67.9M
42.7M
42.7M
33.9M
33.9M
30.9M
30.9M
$37.3M
$37.3M
$40.2M
57.8M
57.8M
$54.3M
31.0M
31.0M
31.7M
31.7M
53.4M
53.4M
31.0M
31.0M
51.2M
51.2M
30.6M
30.6M
33.6M
33.6M
64.2M
64.2M
52.8M
52.8M
43.9M
43.9M
34.8M
34.8M
114.1M
114.1M
$72.5M
$64.1M
64.3M
64.3M
$32.0M
172.5M
172.5M
193.9M
193.9M
36.4M
36.4M
50.0M
50.0M
$32.6M
52.8M
52.8M
47.8M
47.8M
75.5M
75.5M
$119.2M
$156.5M
63.5M
63.5M
$32.0M
$191.0M
$317.5M
$317.5M
172.5M
172.5M
53.9M
53.9M
46.5M
46.5M
$28.0M
30.5M
30.5M
271.6M
271.6M
58.6M
58.6M
47.7M
47.7M
61.3M
61.3M
32.9M
32.9M
318.3M
318.3M
33.9M
33.9M
31.2M
31.2M
40.3M
40.3M
184.4M
184.4M
193.8M
193.8M
493.7M
493.7M
30.1M
54.7M
30.1M
54.7M
33.7M
33.7M
319.2M
319.2M
43.1M
43.1M
385.2M
385.2M
30.7M
30.7M
31.8M
31.8M
32.4M
32.4M
$69.3M
36.8M
36.8M
170.5M
170.5M
$25.0M
294.4M
4.5M
294.4M
4.5M
37.6M
37.6M
215.9M
215.9M
37.5M
37.5M
31.2M
31.2M
448.2M
448.2M
$30.2M
232.7M
232.7M
36.1M
36.1M
64.8M
64.8M
109.4M
109.4M
156.7M
156.7M
86.6M
86.6M
85.4M
85.4M
$90.0M
41.8M
41.8M
437.9M
437.9M
$34.5M
256.7M
256.7M
97.5M
97.5M
137.5M
137.5M
33.6M
33.6M
52.4M
52.4M
61.7M
61.7M
45.2M
45.2M
37.6M
37.6M
$468.1M
$468.1M
35.4M
35.4M
30.4M
30.4M
33.7M
33.7M
128.7M
128.7M
436.2M
436.2M
98.5M
98.5M
189.3M
189.3M
38.5M
38.5M
135.8M
135.8M
$25.0M
57.2M
57.2M
220.0M
220.0M
389.4M
389.4M
76.2M
76.2M
76.2M
76.2M
130.9M
130.9M
41.8M
41.8M
$25.0M
88.5M
88.5M
46.4M
46.4M
$25.0M
$47.0M
30.8M
30.8M
30.8M
30.8M
$33.4M
107.6M
107.6M
31.2M
31.2M
146.1M
146.1M
43.2M
43.2M
43.5M
43.5M
30.4M
30.4M
59.3M
59.3M
42.2M
42.2M
$28.9M
100.4M
100.4M
32.4M
32.4M
62.6M
62.6M
54.3M
54.3M
35.3M
35.3M
31.2M
31.2M
$25.0M
95.7M
95.7M
44.4M
44.4M
175.9M
175.9M
155.2M
155.2M
$108.2M
81.5M
81.5M
97.5M
97.5M
33.2M
33.2M
44.2M
44.2M
35.7M
35.7M
251.2M
251.2M
52.9M
52.9M
$33.8M
$33.8M
37.5M
37.5M
30.5M
30.5M
45.3M
45.3M
43.0M
43.0M
31.6M
31.6M
70.9M
70.9M
31.1M
31.1M
63.2M
63.2M
162.3M
162.3M
56.4M
56.4M
$32.2M
$50.0M
81.9M
81.9M
308.5M
308.5M
242.9M
242.9M
$34.5M
$53.0M
215.7M
215.7M
31.9M
31.9M
162.9M
162.9M
87.4M
87.4M
$120.0M
41.8M
41.8M
$25.6M
187.1M
187.1M
455.1M
455.1M
469.7M
469.7M
115.5M
115.5M
37.0M
37.0M
40.6M
40.6M
96.9M
96.9M
48.6M
48.6M
51.8M
51.8M
54.4M
54.4M
307.5M
307.5M
$68.3M
$54.0M
36.2M
36.2M
32.2M
32.2M
81.4M
81.4M
112.5M
112.5M
34.2M
34.2M
88.4M
88.4M
70.1M
70.1M
32.1M
32.1M
478.5M
478.5M
387.3M
387.3M
311.6M
311.6M
37.5M
37.5M
116.1M
116.1M
53.4M
53.4M
51.1M
51.1M
72.4M
72.4M
46.6M
46.6M
46.0M
46.0M
32.1M
32.1M
$341.6M
48.2M
48.2M
58.9M
58.9M
82.1M
82.1M
380.2M
380.2M
30.4M
30.4M
30.4M
30.4M
67.6M
67.6M
68.5M
68.5M
$35.6M
109.1M
109.1M
52.5M
52.5M
119.1M
119.1M
44.2M
44.2M
308.0M
308.0M
478.3M
478.3M
31.4M
31.4M
42.3M
42.3M
86.5M
86.5M
149.6M
149.6M
65.2M
65.2M
$36.9M
203.7M
203.7M
$27.5M
79.3M
79.3M
$25.8M
148.5M
148.5M
149.3M
149.3M
$38.1M
80.8M
80.8M
62.8M
62.8M
41.3M
41.3M
63.4M
63.4M
57.9M
57.9M
43.1M
43.1M
190.1M
190.1M
$30.0M
45.5M
45.5M
316.7M
316.7M
$68.4M
$68.4M
135.8M
135.8M
54.8M
54.8M
40.8M
40.8M
77.9M
77.9M
387.5M
387.5M
32.1M
32.1M
89.2M
89.2M
121.6M
121.6M
48.3M
48.3M
34.2M
34.2M
36.6M
36.6M
99.3M
99.3M
$150.0M
$26.3M
45.8M
45.8M
$45.6M
31.2M
31.2M
32.1M
32.1M
42.2M
42.2M
$40.0M
191.7M
191.7M
$25.0M
348.4M
348.4M
72.7M
72.7M
$28.0M
61.7M
61.7M
$44.1M
$25.0M
$100.0M
168.4M
168.4M
49.9M
49.9M
294.8M
294.8M
40.4M
40.4M
45.0M
45.0M
$45.5M
131.1M
131.1M
392.3M
392.3M
31.3M
31.3M
44.2M
44.2M
78.5M
78.5M
56.1M
56.1M
64.4M
64.4M
126.5M
126.5M
53.5M
53.5M
$39.4M
45.5M
45.5M
257.2M
257.2M
31.4M
31.4M
71.9M
71.9M
379.7M
379.7M
356.8M
356.8M
47.5M
47.5M
$48.0M
141.8M
141.8M
82.9M
82.9M
41.2M
41.2M
38.4M
38.4M
52.1M
52.1M
267.5M
267.5M
$358.0M
92.4M
92.4M
134.4M
134.4M
$59.8M
259.4M
259.4M
49.1M
49.1M
35.8M
35.8M
33.5M
33.5M
39.3M
$38.0M
39.3M
66.1M
66.1M
55.2M
55.2M
$73.3M
434.5M
434.5M
293.7M
293.7M
44.9M
44.9M
49.4M
49.4M
35.1M
35.1M
$37.5M
48.9M
48.9M
276.1M
276.1M
57.9M
57.9M
31.9M
31.9M
303.8M
303.8M
83.9M
83.9M
306.2M
306.2M
234.9M
234.9M
48.2M
48.2M
40.7M
40.7M
36.3M
36.3M
$25.6M
$42.8M
43.1M
43.1M
43.1M
43.1M
34.3M
34.3M
87.5M
87.5M
31.2M
31.2M
93.5M
93.5M
$59.7M
40.1M
40.1M
70.9M
70.9M
108.6M
108.6M
$41.8M
122.2M
122.2M
34.6M
34.6M
472.3M
472.3M
67.6M
67.6M
43.3M
43.3M
41.7M
41.7M
87.8M
87.8M
36.7M
36.7M
$35.2M
147.5M
147.5M
$25.0M
224.9M
224.9M
42.3M
42.3M
$54.2M
55.0M
55.0M
42.1M
42.1M
$35.0M
38.4M
38.4M
58.3M
58.3M
75.4M
75.4M
8.7M
8.7M
411.5M
411.5M
117.8M
117.8M
457.4M
457.4M
177.4M
177.4M
32.7M
32.7M
$33.3M
$33.3M
$62.0M
41.7M
41.7M
48.7M
48.7M
31.1M
31.1M
43.8M
43.8M
34.8M
34.8M
51.5M
51.5M
194.4M
194.4M
52.2M
52.2M
$37.2M
104.6M
104.6M
38.8M
38.8M
$25.0M
48.4M
48.4M
41.8M
41.8M
79.5M
79.5M
52.9M
52.9M
51.5M
51.5M
251.1M
251.1M
73.7M
73.7M
49.4M
49.4M
$71.2M
$29.4M
$80.0M
$29.9M
91.9M
91.9M
33.8M
33.8M
50.8M
50.8M
37.4M
37.4M
229.2M
229.2M
$30.0M
362.6M
362.6M
116.1M
116.1M
69.6M
69.6M
59.5M
59.5M
68.2M
68.2M
31.1M
31.1M
90.7M
90.7M
$30.4M
180.7M
180.7M
100.0M
100.0M
111.1M
111.1M
$29.6M
34.5M
34.5M
56.6M
56.6M
$44.2M
36.5M
36.5M
131.2M
131.2M
$33.8M
57.5M
57.5M
33.3M
33.3M
63.4M
63.4M
$31.4M
30.1M
30.1M
42.1M
42.1M
$457.6M
$457.6M

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website,revenue_cleaned
0,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com,58000000
1,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com,58000000
2,3-DIMENSIONAL SERVICES GROUP,0,Michigan,72,Motor Vehicle Manufacturing,0,122200000,3dimensional.com,122200000
3,4D SYSTEMS,0,Michigan,82,machinery,0,$32.5M,4dsysco.com,$32.500000
4,50 FLOOR,0,0,170,Retail,0,65498000,http://www.50floor.com,65498000

In [15]:
df_clean['revenue_cleaned'].value_counts()

revenue_cleaned
100000000      73
50000000       70
40000000       68
75000000       65
300000000      62
               ..
$26.300000      1
$150.000000     1
$192000000      1
41875000        1
39900000        1
Name: count, Length: 1044, dtype: int64

In [16]:
# Removed '.' and '$' from the new field 'revenue_new' and casted it to type integer:
df_clean['revenue_cleaned'] = df_clean['revenue_cleaned'].str.replace('[$.]', '', regex =True)
df_clean['revenue_cleaned'] = df_clean['revenue_cleaned'].astype(int)

In [17]:
# Updating column:
df_clean['Revenue'] = df_clean['revenue_cleaned']
# Droping column:
df_clean.drop(columns = ['revenue_cleaned'], inplace = True)

In [18]:
# Getting the statistical values - mean, std, min, max:
stats = df_clean.describe().reset_index()
print(type(stats))
print(stats)

<class 'pandas.core.frame.DataFrame'>
   index       Revenue
0  count  3.016000e+03
1   mean  1.166317e+08
2    std  1.229874e+08
3    min  1.000000e+06
4    25%  3.960900e+07
5    50%  6.200000e+07
6    75%  1.426000e+08
7    max  1.000000e+09

In [19]:
# Getting the median:
median_val  = df_clean['Revenue'].median()
median_val = pd.Series(median_val)
print(type(median_val))
print(median_val)

<class 'pandas.core.series.Series'>
0    62000000.0
dtype: float64

In [20]:
# Added 'median_val' as a row to the 'stats' dataframe:
stats= pd.concat([stats, median_val.to_frame()], ignore_index=True)
print(stats)

   index       Revenue           0
0  count  3.016000e+03         NaN
1   mean  1.166317e+08         NaN
2    std  1.229874e+08         NaN
3    min  1.000000e+06         NaN
4    25%  3.960900e+07         NaN
5    50%  6.200000e+07         NaN
6    75%  1.426000e+08         NaN
7    max  1.000000e+09         NaN
8    NaN           NaN  62000000.0

In [21]:
# Renamed column 'index' as 'Stats':
stats.rename(columns= {'index':'revenue_stats'}, inplace= True)

In [22]:
# Renamed column 'Revenue' as 'values':
stats.rename(columns= {'Revenue': 'values'}, inplace= True)

In [23]:
# Updated the median value correctly:
stats['revenue_stats'][8] = 'median'
stats['values'][8] = stats[0][8]
stats.drop(columns= [0], inplace= True)
stats

C:\Users\yania\AppData\Local\Temp\ipykernel_26960\1251150113.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stats['revenue_stats'][8] = 'median'
C:\Users\yania\AppData\Local\Temp\ipykernel_26960\1251150113.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['revenue_stats'][8] = 'median'
C:\Users\yania\AppData\Local\Temp\ipykernel_26960\1251150113.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stats['values'][8] = stats[0][8]
C:\Users\yania\AppData\Local\Temp\ipykernel_26960\1251150113.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['values'][8] = stats[0][8]

  revenue_stats        values
0         count  3.016000e+03
1          mean  1.166317e+08
2           std  1.229874e+08
3           min  1.000000e+06
4           25%  3.960900e+07
5           50%  6.200000e+07
6           75%  1.426000e+08
7           max  1.000000e+09
8        median  6.200000e+07

In [24]:
# Print CSV stats (mean, median, min, max, etc.,):
stats = stats.to_csv('stats_values.csv', index=False)

Standardizing Employee Size:

In [25]:
# Print a specific column:
new_df = df_clean

In [26]:
# Print unique values:
size_unique = new_df['Employee Size'].unique()
print(size_unique)

['501-1,000' '72' '82' '170' '201-500' '180' '96' '51-200' '130' '73' '59'
 '335' '79' '99' '81' '890' '632' '230' '61' '66' '65' '1,001-5,000' '69'
 '60' '190' '85' '200' '500' '201' '91' '54' '210' '88' '93' '97' '192'
 '360' '57' '1600' '960' '110' '240' '140' '270' '520' '89' '64' '86'
 '250' '650' '150' '450' '94' '370' '232' '1100' '660' '420' '71' '154'
 '55' '120' '410' '160' '92' '310' '490' '63' '62' '970' '67' '430' '280'
 '56' '740' '98' '178' '2300' '68' '380' '260' '460' '582' '580' '596'
 '320' '510' '340' '870' '52' '51' '800' '501' '330' '247' '630' '1500'
 '90' '80' '390' '100' '95' '76' '87' '53' '779' '640' '112' '48530'
 '3000' '350' '213' '78' '990' '3800' '75' '220' '58' '3300' '126' '7100'
 '680' '84' '70' '850' '104' '830' '4448' '790' '1705' '142' '499' '108'
 '145' '789' '1800' '290' '1000' '77' '770' '540' '1200' '910' '440' '920'
 '750' '83' '4000' '378' '1700' '760' '1119' '109' '5,001-10,000' '300'
 '2083' '5001' '74' '2800' '1400' '550' '570' '1300' '810' '798' '940'
 '860' '1392' '618' '620' '2200' '5000' '153' '600' '470' '480' '1900'
 '1001' '5200' '50' '590' '530' '1175' 'seven' '11000' '184' '5500' '165'
 '400' '7200' '560' '930' '204' '459' '259' '124' '234' '161']

In [27]:
new_df['Employee Size'] = new_df['Employee Size'].apply(lambda x: x.strip())

In [28]:
from word2number import w2n

In [29]:
# Converting alphabetic values in Employee Size to numeric values:

for i in range(len(new_df)):
    x = str(new_df.loc[i,'Employee Size'])
    
    if x.isalpha():
        new_df.loc[i,'Employee Size'] = w2n.word_to_num(new_df.loc[i,'Employee Size'])
        
    else:
        new_df.loc[i,'Employee Size'] = new_df.loc[i,'Employee Size']

new_df['Employee Size'] = new_df['Employee Size'].astype(str)

In [30]:
# Print unique values:
size_unique = new_df['Employee Size'].unique()
print(size_unique)

['501-1,000' '72' '82' '170' '201-500' '180' '96' '51-200' '130' '73' '59'
 '335' '79' '99' '81' '890' '632' '230' '61' '66' '65' '1,001-5,000' '69'
 '60' '190' '85' '200' '500' '201' '91' '54' '210' '88' '93' '97' '192'
 '360' '57' '1600' '960' '110' '240' '140' '270' '520' '89' '64' '86'
 '250' '650' '150' '450' '94' '370' '232' '1100' '660' '420' '71' '154'
 '55' '120' '410' '160' '92' '310' '490' '63' '62' '970' '67' '430' '280'
 '56' '740' '98' '178' '2300' '68' '380' '260' '460' '582' '580' '596'
 '320' '510' '340' '870' '52' '51' '800' '501' '330' '247' '630' '1500'
 '90' '80' '390' '100' '95' '76' '87' '53' '779' '640' '112' '48530'
 '3000' '350' '213' '78' '990' '3800' '75' '220' '58' '3300' '126' '7100'
 '680' '84' '70' '850' '104' '830' '4448' '790' '1705' '142' '499' '108'
 '145' '789' '1800' '290' '1000' '77' '770' '540' '1200' '910' '440' '920'
 '750' '83' '4000' '378' '1700' '760' '1119' '109' '5,001-10,000' '300'
 '2083' '5001' '74' '2800' '1400' '550' '570' '1300' '810' '798' '940'
 '860' '1392' '618' '620' '2200' '5000' '153' '600' '470' '480' '1900'
 '1001' '5200' '50' '590' '530' '1175' '7' '11000' '184' '5500' '165'
 '400' '7200' '560' '930' '204' '459' '259' '124' '234' '161']

In [31]:
# Standardizing the Employee Size values into groups of -
# '0-50', '51-200', '201-500', '501-1000', '1,001-5,000', '5,001-10,000', '10,001+'

for i in range(len(new_df)):
    try:
        if new_df.loc[i,'Employee Size'].isnumeric():
            x = int(new_df.loc[i,'Employee Size'])

            if x<=50:
                new_df.loc[i,'Employee Size'] = '0-50'

            elif 51 <= x <=200:
                new_df.loc[i, 'Employee Size'] = '51-200'

            elif 201 <= x <=500:
                new_df.loc[i, 'Employee Size'] = '201-500'

            elif 501 <= x <=1000:
                new_df.loc[i, 'Employee Size'] = '501-1,000'

            elif 1001 <= x <=5000:
                new_df.loc[i, 'Employee Size'] = '1,001-5,000'

            elif 5001 <= x <=10000:
                new_df.loc[i, 'Employee Size'] = '5,001-10,000'

            elif x >=10001:
                new_df.loc[i, 'Employee Size'] = '10,001+'
                
        else:
            
            if (new_df.loc[i, 'Employee Size'] == '11-50'):
                new_df.loc[i, 'Employee Size'] = '0-50'

            else:
                new_df.loc[i, 'Employee Size'] = new_df.loc[i, 'Employee Size']
                
    except ValueError:
        print("does not work")
 
new_df.reset_index(drop=True, inplace= True)

In [32]:
# Print unique values:
size_unique = new_df['Employee Size'].unique()
print(size_unique)

['501-1,000' '51-200' '201-500' '1,001-5,000' '10,001+' '5,001-10,000'
 '0-50']

In [33]:
new_df.tail()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
3011,ZIPPO MANUFACTURING COMPANY,0,Pennsylvania,"501-1,000",Mechanical Or Industrial Engineering,0,230000000,zippo.com
3012,ZOLL,0,0,"1,001-5,000",Medical Equipment Manufacturing,0,457600000,https://www.zoll.com/
3013,ZOLL,https://www.linkedin.com/company/zoll-medical-...,Massachusetts,"1,001-5,000",Medical Equipment Manufacturing,0,457600000,https://www.zoll.com/
3014,ZUMBIEL,0,0,51-200,Packaging & Containers,0,30402000,zumbiel.com
3015,ZUMBIEL,0,Kentucky,51-200,Packaging & Containers,0,30402000,zumbiel.com

# Creating a new feature 'Company type':
 Grouping companies into small, medium, and large enterprises:

In [ ]:
# Creating a new calculated field 'Company type':
# --to categorizes companies as 'Small Enterprise', 'Medium Enterprise', 'Large Enterprise',..
# ...'unicorn', 'abnormal'

company_type = []
for i in range(len(new_df)):
    x = new_df.loc[i, 'Employee Size']
    y = new_df.loc[i, 'Revenue'] 
    
    if ((y < 38500000)&((x == '0-50')|(x == '51-200')|(x == '201-500')|(x == '501-1,000')|(x == '1,001-5,000')|(x == '5,001-10,000')|(x == '10,001+'))):
        c_type = 'Small Enterprise'
        company_type.append(c_type)    
    
    elif ((38500000 <= y < 500000000)&((x == '0-50')|(x == '51-200')|(x == '201-500')|(x == '501-1,000')|(x == '1,001-5,000')|(x == '5,001-10,000')|(x == '10,001+'))):
        c_type = 'Medium Enterprise'
        company_type.append(c_type)

    elif ((500000000 <= y < 1000000000)&((x == '201-500')|(x == '501-1,000')|(x == '1,001-5,000')|(x == '5,001-10,000')|(x == '10,001+'))):
        c_type = 'Large Enterprise'
        company_type.append(c_type)
    
    elif ((y >= 500000000)&((x == '0-50')|(x == '51-200')|(x == '201-500')|(x == '501-1,000'))):
        c_type = 'unicorn'
        company_type.append(c_type)

        
    else:
        c_type = 'abnormal'
        company_type.append(c_type)
 
new_df['Company type'] = company_type

In [35]:
new_df['Company type'].value_counts()

Company type
Medium Enterprise    2233
Small Enterprise      724
Large Enterprise       51
unicorn                 8
Name: count, dtype: int64

In [ ]:
# Checking sample:
new_df.sample(10)

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website,Company type
1606,LINCOLN ELECTRIC,https://www.linkedin.com/company/10281,Ohio,"5,001-10,000",machinery,0,328600000,lincolnelectric.com,Medium Enterprise
1017,FORTEC MEDICAL,https://www.linkedin.com/company/279513,Ohio,201-500,Medical Equipment Manufacturing,0,32900000,https://www.fortecmedical.com,Small Enterprise
1871,NATIONAL BUSINESS FURNITURE,0,0,201-500,Furniture and Home Furnishings Manufacturing,0,119100000,https://www.nationalbusinessfurniture.com/,Medium Enterprise
2406,SHAPE PROCESS AUTOMATION,https://www.linkedin.com/company/1333868,Michigan,201-500,Automation Machinery Manufacturing,0,57900000,http://www.shapeprocessautomation.com,Medium Enterprise
65,AEROSTAR (AEROSTAR INTERNATIONAL LLC),0,South Dakota,51-200,Defense and Space Manufacturing,0,25000000,aerostar.com,Small Enterprise
2644,TERVIS,0,Florida,201-500,Retail,0,110000000,http://www.tervis.com,Medium Enterprise
2963,WISCONIC,0,Wisconsin,51-200,plastics,0,44200000,wisconic.com,Medium Enterprise
1758,MICHIGAN SUGAR,https://linkedin.com/company/michigan-sugar-co,Michigan,"1,001-5,000",Food and Beverage Manufacturing,0,46600000,http://www.michigansugar.com,Medium Enterprise
805,DURATECH INDUSTRIES,https://linkedin.com/company/duratech-industries,Wisconsin,201-500,Printing Services,0,45000000,http://www.duratech.com,Medium Enterprise
1171,GT,0,0,"1,001-5,000",Motor Vehicle Manufacturing,0,38520000,http://www.gttechnologies.com,Medium Enterprise

In [37]:
new_df.to_csv('company_list_new.csv',index= False)

In [38]:
# Delete output:

import os
os.remove('stats_values.csv')
os.remove('company_list_new.csv')